import os
import pandas as pd
from mcp.server.fastmcp import FastMCP

# Ensure this path matches where main.py saves files
UPLOADS_DIR = r"C:\Users\user\Desktop\Local-Chatbot\backend\uploads"

mcp = FastMCP("excel-server")

@mcp.tool()
def execute_excel_query(filename: str, code: str):
    """Execute Python pandas code on an uploaded Excel file safely"""
    filepath = os.path.join(UPLOADS_DIR, filename)
    
    if not os.path.exists(filepath):
        return f"File not found. Available: {os.listdir(UPLOADS_DIR)}"

    # Set up a namespace for the code to run in
    # 'filename' is passed so the LLM code can use pd.read_excel(filename)
    local_vars = {"pd": pd, "filename": filepath, "result": None}
    
    try:
        # Execute the code string provided by the LLM
        exec(code, {}, local_vars)
        
        # main.py expects a string representation of a dictionary
        # the prompt tells the LLM to store the dict in 'result'
        return str(local_vars.get("result", "No result generated by code."))
    except Exception as e:
        return f"Python Execution Error: {str(e)}"

if __name__ == "__main__":
    mcp.run()